spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user_management
              uri: http://user-management:8081
              predicates:
                - Path=/users,/users/**
                - Method=POST,PUT,DELETE
            - id: car_registry
              uri: http://car-registry:8082
              predicates:
                - Path=/cars
                - Method=POST
            - id: car_booking
              uri: http://car-booking:8083
              predicates:
                - Path=/cars,/bookings,/bookings/**
