apiVersion: v1
kind: ConfigMap
metadata:
  name: car-sharing-config
  namespace: car-sharing
data:
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_USERNAME: guest
  SPRING_RABBITMQ_PASSWORD: guest
  OTEL_EXPORTER_OTLP_ENDPOINT: http://openobserve:5080/api/default
  OTEL_EXPORTER_OTLP_HEADERS: Authorization=Basic YWRtaW5AZXhhbXBsZS5jb206QWRtaW5AMTIzNA==
  OTEL_LOGS_EXPORTER: otlp
